title:             Nikhil Rao
email:             nikhil@nikhilrao.me
description:       Welcome to my site!
author:            Nikhil Rao
baseurl:           ""
url:               "https://nikhilrao.me"

# Social Profiles
github_username:   picklelo
linkedin_username: nrao95

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
