title: Nikhil Rao's Website
email: nikhil@nikhilrao.me
description: Welcome to my blog!
baseurl: ""
url: "https://nikhilrao.me"
github_username:  picklelo
linkedin_username: nrao95

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
